### ISSUE TITLE
Investigate flaky tests for python agent. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-integration-testing#73] opened 2018-05-22 09:29 UTC
After fixing some bugs and after merging a version update PR for the python agent tests became flaky for the python agent, see e.g. https://apm-ci.elastic.co/job/elastic+apm-integration-testing+master+multijob-python-agent-versions/205/.

`tornado` is used to send concurrent requests to the example apps. This works fine with other agents and apps, but for the python apps we do receive `500` responses since last week. 
see e.g.

```
13:46:50 ----------------------------- Captured stderr call -----------------------------
13:46:50 [2018-05-21 13:44:42,693] [10] [INFO] [run -             263]  Testing started..
13:46:50 [2018-05-21 13:44:42,693] [10] [INFO] [run -             263]  Testing started..
13:46:50 [2018-05-21 13:44:42,747] [10] [INFO] [run -             267]  Sending batch 1 / 1
13:46:50 [2018-05-21 13:44:42,747] [10] [INFO] [run -             267]  Sending batch 1 / 1
13:46:50 [2018-05-21 13:44:42,820] [10] [INFO] [load_test -             101]  Starting tornado I/O loop
13:46:50 [2018-05-21 13:44:42,820] [10] [INFO] [load_test -             101]  Starting tornado I/O loop
13:46:50 [2018-05-21 13:44:50,074] [10] [ERROR] [handle -             85]  Bad response, aborting: 500 - HTTP 500: INTERNAL SERVER ERROR (0.24900579452514648)
13:46:50 [2018-05-21 13:44:50,074] [10] [ERROR] [handle -             85]  Bad response, aborting: 500 - HTTP 500: INTERNAL SERVER ERROR (0.24900579452514648)
13:46:50 ioloop.py                  638 ERROR    Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fcb65a072f0>, HTTPResponse(_body=None,buffer=<_io.BytesIO object at 0x7fcb65fb8780>,code=500,effective_url='http://flaskapp:8001/bar?q=1',error=HTTP 500: INTERNAL SERVER ERROR,headers=<tornado.httputil.HTTPHeaders object at 0x7fcb65a0c9e8>,reason='INTERNAL SERVER ERROR',request=<tornado.httpclient.HTTPRequest object at 0x7fcb65a00d68>,request_time=0.24900579452514648,time_info={}))
13:46:50 Traceback (most recent call last):
13:46:50   File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
13:46:50     ret = callback()
13:46:50   File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
13:46:50     return fn(*args, **kwargs)
13:46:50   File "/app/tests/agent/concurrent_requests.py", line 86, in handle
13:46:50     raise Exception(message)
13:46:50 Exception: Bad response, aborting: 500 - HTTP 500: INTERNAL SERVER ERROR (0.24900579452514648)
```

**Comment by graphaelli** [comment] 2018-06-05 19:32
reproduced this post #77 -

```
export REUSE_CONTAINERS=1
./scripts/ci/versions_python.sh 'release;latest' 6.2
./venv/bin/pytest tests/agent/test_python.py::test_concurrent_req_flask_foobar -v
```

trying to track it down

**Comment by graphaelli** [comment] 2018-06-05 19:48
I can't prove it yet but I think the flask development server just isn't keeping up sometimes.  Lowering max_clients from 4 to 2 seems to make these tests pass consistently.

@beniwohli any thoughts on whether that's likely the cause / how to prove it or alternatives for solving the problem?

**Comment by graphaelli** [comment] 2018-06-05 20:27
I take that theory back.  With flask in debug mode, the body of the first failed request is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1834, in finalize_request
    request_finished.send(self, response=response)
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/elasticapm/contrib/flask/__init__.py", line 151, in request_finished
    self.client.end_transaction(rule, result)
  File "/usr/local/lib/python3.6/site-packages/elasticapm/base.py", line 257, in end_transaction
    self._collect_transactions()
  File "/usr/local/lib/python3.6/site-packages/elasticapm/base.py", line 297, in _collect_transactions
    self._stop_send_timer()
  File "/usr/local/lib/python3.6/site-packages/elasticapm/base.py", line 324, in _stop_send_timer
    self._send_timer.join()
  File "/usr/local/lib/python3.6/threading.py", line 1051, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
```

**Comment by beniwohli** [comment] 2018-06-05 20:57
@graphaelli That's quite possibly a bug in the agent. It probably shuts down the agent before the timer thread started, and the shutdown logic unconditionally tries to join that timer thread... At least that's what I'm guessing from that stack trace. I'll have a closer look tomorrow, feel free to open an issue in the meantime

**Comment by graphaelli** [comment] 2018-06-05 21:30
That's what I was worried about.  https://github.com/elastic/apm-agent-python/issues/222 opened.

**Comment by graphaelli** [comment] 2018-06-06 01:28
#84 seems to resolve this flakiness but I'm not clear on whether it's working around a bug in the agent, a bug in the flask development server (werkzeug.serving), or something else.

**Comment by beniwohli** [comment] 2018-06-06 11:47
I get a whole lot more failures when running the commands from https://github.com/elastic/apm-integration-testing/issues/73#issuecomment-394832586, and it's nigh impossible to tell why, the tests just dump thousands of lines of timeout related messages into my console

**Comment by jalvz** [comment] 2018-06-06 11:56
same here, didn't have time to look more at it yet

**Comment by graphaelli** [comment] 2018-06-06 14:05
The errors are quite verbose when the tests fail, #87 opened to at least track fixing that.

Closing this one out since #84 landed.  We can reopen if a trend reemerges.

**Closed by graphaelli** 2018-06-06 14:05 UTC
Labels: bug

**Comment by beniwohli** [comment] 2018-06-12 08:45
Looks like the Python tests now pass again with some regularity https://apm-ci.elastic.co/job/elastic+apm-integration-testing+master+multijob-python-agent-versions/
